version: "3.7"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mojabaza:/var/lib/mysql
    networks:
      - mojnet
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mojnet
    
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mojnet
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - SECRET=0f1j0ewfje0fdsfi
    networks:
      - mojnet

networks:
  mojnet:
    driver: "bridge"

volumes:
  mojabaza:
  