install:
	go get -u github.com/labstack/echo
	#go get -u github.com/go-xorm/xorm
	go get -u github.com/go-sql-driver/mysql
	go get -u golang.org/x/sys/unix
	go get -u golang.org/x/crypto/bcrypt
	go get -u github.com/dgrijalva/jwt-go
	
	#go get -u github.com/kerlexov/hbxpack
